version: '2'

services:

### Workspace Utilities Container ###########################
    nodejs:
        image: node:6.9.5-alpine
        ports:
            - "8080:8080"
        tty: true
        volumes:
            - ".:/usr/app"

### Add more Containers below ###############################
# use [ docker network create microservicenetwork ] เพื่อสร้าง mapmagiccloud(your network name้) network ขึ้นมาก่อน
networks:
    default:
        external:
            name: microservicenetwork
